### ISSUE TITLE
Consider pinning `avr-hal` revision

### ISSUE THREAD

**Issue by Rahix** [bbonenfant/avr-dot-games#6]
Hey!

Just wanted to let you know that you should probably pin the version of `avr-hal` in `Cargo.toml` to a specific git revision.  `avr-hal` is still quite early in development and newer versions might break your code so this way anyone downloading the project and trying to compile it in the future will build against the same version of `avr-hal` that you originally worked with.

In practical terms, this means specifying the dependency in `Cargo.toml` like this:

```toml
[dependencies.arduino-uno]
git = "https://github.com/Rahix/avr-hal"
rev = "7337cd76cd96f2d27701b137396d94a06d3a501d"
```

([`7337cd76cd96`](https://github.com/Rahix/avr-hal/commit/7337cd76cd96f2d27701b137396d94a06d3a501d) is the latest commit on master, you should probably check whether that still works for you and use an older one instead if it does not ...)
